### ISSUE TITLE
Deprecate Old Package

### ISSUE THREAD

**Issue by sir-captainmorgan21** [atwwei/dfp#2]
You may want to "deprecate" your angular 6 package.

**Comment by atwwei** [comment]
> You may want to "deprecate" your angular 6 package.

I don't understand what you mean. Please describe it in detail.

**Comment by sir-captainmorgan21** [comment]
Ahh nvm. I saw you also had ngx-dfp and understood it to be a new and improved version of this package. My mistake. Are you still maintaining this? Its behind on Angular versions.

**Comment by atwwei** [comment]
> Ahh nvm. I saw you also had ngx-dfp and understood it to be a new and improved version of this package. My mistake. Are you still maintaining this? Its behind on Angular versions.

The structure of `ngx-dfp` is complex, which is not conducive to use and maintenance, so I chose to rewrite it as `@wwei/dfp`. 

`ngx-dfp` is no longer actively maintained, but not deprecated.  If you have any needs, you can directly explain in the new issue, and I will try my best to help.

**Comment by sir-captainmorgan21** [comment]
You are right. I got mixed up with the names being so similar. We are using ngx-dfp. I was suggesting deprecating `ngx-dfp` or at the very least, pointing to `@wwei/dfp` from that repo's README.md. I think it should be deprecated, as it will likely begin to straight up not work in more recent versions of Angular. Any plans to upgrade this package to NG 13? I can create a PR if you have a lot going on.

**Comment by atwwei** [comment]
I see, I'm going to deprecate the package to avoid mixing.

Thanks for your suggestion.

**Comment by sir-captainmorgan21** [comment]
Awesome thanks!
