### ISSUE TITLE
GPT error on page change in console ([Object Object])

### ISSUE THREAD

**Issue by haegemonia76** [atwwei/dfp#3]
Hello, First let met express my thanks to you for doing this awesome package ! Thank You ! :)

Currently using Angular 11, and each time i change page in the console i saw this error :
<img width="847" alt="image" src="https://user-images.githubusercontent.com/10331012/160416096-dc36cade-257a-49d4-a6e8-f9bb8aafb59e.png">

Is there a way to hide or fix this error display ?

**Comment by atwwei** [comment]
@haegemonia76

Although the problem can be avoided by modification, it should not occur under normal circumstances.

GTP prompts this question, indicating that the defined slot is invalid. A guess might be that the element id has changed.

Alternatively, test code can be provided to identify specific problems.
